name: BedWars
version: 1.0
api: [3, 4]
main: BedWars\BedWars
author: HixX
description: BedWars plugin
depend: [MTCore]

commands:
    bw:
        description: "main bedwars command"
    blue:
        description: "join to blue team"
    red:
        description: "join to red team"
    yellow:
        description: "join to yellow team"
    green:
        description: "join to green team"
    lobby:
        description: "send to main lobby"
    stats:
        description: "show your game stats"
    vote:
        description: "vote command"
